# Generated by Django 3.0.2 on 2020-06-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtweet',
            name='author_by',
            field=models.CharField(max_length=255),
        ),
    ]
