# Generated by Django 3.0.2 on 2020-06-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200614_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listtweet',
            name='type',
        ),
        migrations.AddField(
            model_name='listtweet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listtweet',
            name='author_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listtweet',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
