# Generated by Django 3.0.2 on 2020-06-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200618_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listtweet',
            old_name='author_by',
            new_name='author',
        ),
    ]
