# Generated by Django 3.0.2 on 2020-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200621_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtweet',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
