# Generated by Django 3.0.2 on 2021-02-12 07:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200621_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtweet',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
